### ISSUE TITLE
affirmative/roger sound bug

### ISSUE THREAD

**Issue by Ayrton09** [rogeraabbccdd/CSGO-Custom-Radio-Sounds#1]
hello kento, when Affirmative/Roger that. "affirmative" is the only who trigger a sound but the roger command dont trigger any sound, i tried to set in cfg this but seems like its not working for some reason.sorry bad english.

"affirmative"	"custom_radio/anime/yes.mp3"
"agree"	        "custom_radio/anime/yes.mp3"

**Comment by rogeraabbccdd** [comment]
I found the problem, it has two different radio text message, `affirmative` and `rogerthat`.
I'm checking all radio commands.

**Comment by rogeraabbccdd** [comment]
It should be fixed. Let me know if I miss something.

**Comment by Ayrton09** [comment]
fixed! arigato gozaimasu.
