### ISSUE TITLE
cheer! command doesnt work.

### ISSUE THREAD

**Issue by Ayrton09** [rogeraabbccdd/CSGO-Custom-Radio-Sounds#2]
hello kento how are you?, if you have some time can you fix or add the "cheer!" radio command..thanks!

**Comment by rogeraabbccdd** [comment]
Hello, sorry for late reply.
What's the map when this happening?

**Comment by Ayrton09** [comment]
in no one map works, i would like to use cheer for nice anime voice, etc :P

**Comment by rogeraabbccdd** [comment]
Works for me.
It should be `onarollbrag` in your cfg, not `cheer`.
